### PR TITLE
make install.sh executable

### PR DESCRIPTION
**Pull request by thaJeztah**
this shouldn't affect users downloading, but makes it easier to debug the script while making changes.

### CODE REVIEW

**Comment by thaJeztah** [comment]
@StefanScherer @silvin-lubecki ptal

**Review by silvin-lubecki — APPROVED** [review]
LGTM, always weird to review something that has `No changes` 😆

**Comment by thaJeztah** [comment]
yeah, they should make file-mode changes more visible; really easy to miss if they're changed accidentally

**Review by StefanScherer — APPROVED** [review]
Sure!
LGTM

**Pull request merged**
