### PR TITLE
Fix installation on debian testing (bookworm) (carry 327)

### PR DESCRIPTION
**Pull request by thaJeztah**
- carries https://github.com/docker/docker-install/pull/327
- closes https://github.com/docker/docker-install/pull/327

We published packages now for Debian 12 (bookworm) for testing, so we can
update this to use the correct version;
https://download.docker.com/linux/debian/dists/bookworm/pool/stable/amd64/

### CODE REVIEW

**Comment by orgads** [comment]
Thank you. Please fix the commit message accordingly.

**Comment by thaJeztah** [comment]
> Thank you. Please fix the commit message accordingly.

Oh! Good catch. I wanted to, and then forgot 😂
Let me update

**Comment by thaJeztah** [comment]
Oh! I updated; PTAL

@crazy-max @laurazard

**Review by laurazard — APPROVED** [review]
LGTM

**Pull request merged**
