### PR TITLE
rootless: move versions together

### PR DESCRIPTION
**Pull request by thaJeztah**
- follow-up to https://github.com/docker/docker-install/pull/428

Cleaning up my local branches; I had this stashed as part of the above PR, but at the time decided to keep it for a follow-up 😂

### CODE REVIEW

**Review by krissetto — APPROVED** [review]

**Review by sam-thibault — APPROVED** [review]

**Comment by vvoland** [comment]
The separation was actually introduced on purpose https://github.com/docker/docker-install/pull/404 🙈

**Comment by thaJeztah** [comment]
🤦 DOH!

**Comment by thaJeztah** [comment]
Oh; but I think this still works, because we now have the comment in between them; before https://github.com/docker/docker-install/pull/404 they were next to each other, which is what the problematic part was; https://github.com/docker/docker-install/blob/c938c5c478b5d6a31537634f5ce5a8df93e8cbe2/rootless-install.sh#L31-L33

And we now have a comment in between, which probably prevents merge-conflicts because of that separation 🤞 https://github.com/docker/docker-install/blob/1ce4e39c9502b89728cdd4790a8c3895709e358d/rootless-install.sh#L23-L27

**Comment by thaJeztah** [comment]
And if it doesn't work; blame me! 🫶 🫶 🫶

**Pull request merged**
