### PR TITLE
Use add-apt-repository if available.

### PR DESCRIPTION
**Pull request by dHannasch**
add-apt-repository is capable of seamlessly handling proxy settings.

### CODE REVIEW

**Comment by seemethere** [comment]
iirc the reason we had originally decided against it was that `add-apt-repository` was bugged for `arm` variations of `ubuntu` and `debian`.

**Comment by seemethere** [comment]
Related issue: https://github.com/moby/moby/issues/31405

**Comment by thaJeztah** [comment]
(Going through some old PRs); yes, I think this was A) because of the incompatibility mentioned, B) to reduce the number of dependencies needed to install (just for adding a line to a file), and C) manually creating the file gives a consistent filename for users to look for the repository config (it will always be in `/etc/apt/sources.list.d/docker.list`), which helps in some situations (e.g. when upgrading distros etc).

Let me close this PR, but thanks for contributing!

**Comment by dHannasch** [comment]
Actually, taking another look at this, I think we can totally make this work manually.

**Comment by dHannasch** [comment]
I don't understand the question (is there a difference?), but regardless, looks like the automated install totally works without this change, including behind a proxy. https://gitlab.com/shell-bootstrap-scripts/register-gitlab-runner/-/blob/master/install-docker.sh#L69
I thought that I'd had to use this branch to make it work, but I must have misremembered.

**Pull request closed without merging**
