### PR TITLE
rootless-install.sh: bump up to 19.03.5

### PR DESCRIPTION
**Pull request by AkihiroSuda**
Signed-off-by: Akihiro Suda <akihiro.suda.cz@hco.ntt.co.jp>

### CODE REVIEW

**Comment by AkihiroSuda** [comment]
Please also sync https://get.docker.com/rootless after merging this 🙏

**Comment by AkihiroSuda** [comment]
CI failure seems unrelated

```
+ make shellcheck

mkdir -p build

LOAD_SCRIPT_COMMIT_SHA='2ef20de64abcb583c3cdc819da883a7ee1230513' envsubst '$LOAD_SCRIPT_COMMIT_SHA' < install.sh > build/install.sh

docker run --rm -v "/home/ubuntu/workspace/docker-install_PR-149":/v -w /v koalaman/shellcheck -eSC1091 -eSC1117 build/install.sh

Unable to find image 'koalaman/shellcheck:latest' locally

latest: Pulling from koalaman/shellcheck

9a777a079ad1: Pulling fs layer

09ee0c91bff5: Pulling fs layer

09ee0c91bff5: Download complete

9a777a079ad1: Verifying Checksum

9a777a079ad1: Download complete

9a777a079ad1: Pull complete

09ee0c91bff5: Pull complete

Digest: sha256:10ec80688125915f6a5b8e829a990dffeb0054b81a18194c9e6698a64ae24ddc

Status: Downloaded newer image for koalaman/shellcheck:latest

shellcheck: src/ShellCheck/Analytics.hs:1404:10-27: No instance nor default method for class operation mappend



Makefile:20: recipe for target 'shellcheck' failed

make: *** [shellcheck] Error 1

script returned exit code 2
```

**Comment by AkihiroSuda** [comment]
@zelahi PTAL?

**Comment by zelahi** [comment]
Will look into the CI failure

**Comment by AkihiroSuda** [comment]
@zelahi could you sync https://get.docker.com/rootless ?

**Pull request merged**
