### PR TITLE
rootless-install.sh: bump up test channel to 20.10.0-rc1

### PR DESCRIPTION
**Pull request by AkihiroSuda**

### CODE REVIEW

**Comment by AkihiroSuda** [comment]
@StefanScherer @thaJeztah @tiborvass PTAL

**Review by thaJeztah — APPROVED** [review]
LGTM

**Review by StefanScherer — APPROVED** [review]
LGTM

Thank you!

**Comment by StefanScherer** [comment]
Reminder: Trigger a build https://ci-next.docker.com/teams-core/job/get.docker.com/job/upload-rootless-install/
Maybe we could hook up a automatic publish when we merge to master.

**Comment by thaJeztah** [comment]
@StefanScherer do you recall if the build was triggered? What's needed to make it automatic?

**Comment by StefanScherer** [comment]
@thaJeztah Yes, I've triggered the build. For an automated trigger we could set up a Jenkins pipeline that triggers on master  branch. I can take a look in the jenkins job that we already have...

**Pull request merged**
