### PR TITLE
add URLs of docs to headers

### PR DESCRIPTION
**Pull request by AkihiroSuda**
Without the URL of the docs, it is hard to understand the intention of the script.

### CODE REVIEW

**Comment by AkihiroSuda** [comment]
@StefanScherer @thaJeztah PTAL

**Comment by thaJeztah** [comment]
There's a bug on GitHub where, after you mark a check as "required", it will be _added_ to existing  PR's, but never actually run (or complete) 😞 

Jenkins ran on this one, and was green (didn't expect otherwise), so I'll "use the force" and merge this one

**Comment by AkihiroSuda** [comment]
@StefanScherer Could you trigger Jenkins to update https://get.docker.com/ ?

**Comment by StefanScherer** [comment]
Done. Thanks @AkihiroSuda for the heads-up.

**Comment by AkihiroSuda** [comment]
Thanks!

**Pull request merged**
