### PR TITLE
Add temporary Ubuntu Artful support

### PR DESCRIPTION
**Pull request by seemethere**
Adds temporary support for Ubuntu Artful while we wait to get packages
up, after we do get packages up we should delete the lines denoted `#TODO: DELETE HERE`

Signed-off-by: Eli Uriegas <eli.uriegas@docker.com>

### CODE REVIEW

**Comment by seemethere** [comment]
Waiting on merge for tests to run

**Comment by FrenchBen** [comment]
Confirmed to be working as expected.
```
$ cat /etc/lsb-release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=17.10
DISTRIB_CODENAME=artful
DISTRIB_DESCRIPTION="Ubuntu 17.10"
$ docker version
Client:
 Version:      17.10.0-ce
 API version:  1.33
 Go version:   go1.8.3
 Git commit:   f4ffd25
 Built:        Tue Oct 17 19:05:05 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.10.0-ce
 API version:  1.33 (minimum version 1.12)
 Go version:   go1.8.3
 Git commit:   f4ffd25
 Built:        Tue Oct 17 19:03:46 2017
 OS/Arch:      linux/amd64
 Experimental: false
```

**Comment by BigNerd95** [comment]
I receive the following error:
```
# Executing docker install script, commit: UNKNOWN
+ sudo -E sh -c 'apt-get update -qq >/dev/null'
E: The repository 'https://download.docker.com/linux/ubuntu artful Release' does not have a Release file.
```

**Comment by BigNerd95** [comment]
I receive the following error:
```
# Executing docker install script, commit: 49ee7c1
+ sudo -E sh -c 'apt-get update -qq >/dev/null'
E: The repository 'https://download.docker.com/linux/ubuntu artful Release' does not have a Release file.
```

**Comment by seemethere** [comment]
@BigNerd95 Can we have some more information about your system?

What's the output of `cat /etc/os-release`?

**Comment by darwin** [comment]
Same problem here. Digital Ocean VPS, Ubuntu 17.04. Maybe some kind of Digital Ocean packages caching?

```
> cat /etc/os-release
NAME="Ubuntu"
VERSION="17.04 (Zesty Zapus)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 17.04"
VERSION_ID="17.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=zesty
UBUNTU_CODENAME=zesty
```

```
> do-release-upgrade
Checking for a new Ubuntu release
Get:1 Upgrade tool signature [819 B]
Get:2 Upgrade tool [1,255 kB]
Fetched 1,256 kB in 0s (0 B/s)
authenticate 'artful.tar.gz' against 'artful.tar.gz.gpg'
extracting 'artful.tar.gz'

Reading cache

Checking package manager
Reading package lists... Done
Building dependency tree
Reading state information... Done
Hit http://security.ubuntu.com/ubuntu zesty-security InRelease
Hit http://ams2.mirrors.digitalocean.com/ubuntu zesty InRelease
Hit http://ams2.mirrors.digitalocean.com/ubuntu zesty-updates InRelease
Hit https://apt.dockerproject.org/repo ubuntu-xenial InRelease
Hit https://download.docker.com/linux/ubuntu zesty InRelease
Hit https://repos.sonar.digitalocean.com/apt main InRelease
Fetched 0 B in 0s (0 B/s)
Reading package lists... Done
Building dependency tree
Reading state information... Done
...

Updating repository information

No valid mirror found

While scanning your repository information no mirror entry for the
upgrade was found. This can happen if you run an internal mirror or
if the mirror information is out of date.

Do you want to rewrite your 'sources.list' file anyway? If you choose
'Yes' here it will update all 'zesty' to 'artful' entries.
If you select 'No' the upgrade will cancel.

Continue [yN] y
Get:1 http://security.ubuntu.com/ubuntu artful-security InRelease [70.3 kB]
Get:2 http://ams2.mirrors.digitalocean.com/ubuntu artful InRelease [237 kB]
Get:3 http://ams2.mirrors.digitalocean.com/ubuntu artful-updates InRelease [76.7 kB]
Hit https://apt.dockerproject.org/repo ubuntu-xenial InRelease
Hit https://repos.sonar.digitalocean.com/apt main InRelease
Get:4 http://security.ubuntu.com/ubuntu artful-security/universe Sources [1,144 B]
Ign https://download.docker.com/linux/ubuntu artful InRelease
Get:5 http://security.ubuntu.com/ubuntu artful-security/main Sources [2,448 B]
Get:6 http://ams2.mirrors.digitalocean.com/ubuntu artful/universe Sources [8,721 kB]
Get:7 http://security.ubuntu.com/ubuntu artful-security/main amd64 Packages [5,620 B]
Err https://download.docker.com/linux/ubuntu artful Release
  404  Not Found
Get:8 http://security.ubuntu.com/ubuntu artful-security/main i386 Packages [5,620 B]
Get:9 http://security.ubuntu.com/ubuntu artful-security/main Translation-en [2,364 B]
Get:10 http://security.ubuntu.com/ubuntu artful-security/universe amd64 Packages [2,372 B]
Get:11 http://security.ubuntu.com/ubuntu artful-security/universe i386 Packages [2,376 B]
Get:12 http://security.ubuntu.com/ubuntu artful-security/universe Translation-en [1,400 B]
Get:13 http://ams2.mirrors.digitalocean.com/ubuntu artful/main Sources [849 kB]
Get:14 http://ams2.mirrors.digitalocean.com/ubuntu artful/main i386 Packages [1,067 kB]
Get:15 http://ams2.mirrors.digitalocean.com/ubuntu artful/main amd64 Packages [1,071 kB]
Get:16 http://ams2.mirrors.digitalocean.com/ubuntu artful/main Translation-en [542 kB]
Get:17 http://ams2.mirrors.digitalocean.com/ubuntu artful/universe amd64 Packages [8,103 kB]
Get:18 http://ams2.mirrors.digitalocean.com/ubuntu artful/universe i386 Packages [8,066 kB]
Get:19 http://ams2.mirrors.digitalocean.com/ubuntu artful/universe Translation-en [4,789 kB]
Get:20 http://ams2.mirrors.digitalocean.com/ubuntu artful-updates/main Sources [4,524 B]
Get:21 http://ams2.mirrors.digitalocean.com/ubuntu artful-updates/universe Sources [1,144 B]
Get:22 http://ams2.mirrors.digitalocean.com/ubuntu artful-updates/main amd64 Packages [7,676 B]
Get:23 http://ams2.mirrors.digitalocean.com/ubuntu artful-updates/main i386 Packages [7,688 B]
Get:24 http://ams2.mirrors.digitalocean.com/ubuntu artful-updates/main Translation-en [3,400 B]
Get:25 http://ams2.mirrors.digitalocean.com/ubuntu artful-updates/universe amd64 Packages [3,228 B]
Get:26 http://ams2.mirrors.digitalocean.com/ubuntu artful-updates/universe i386 Packages [3,236 B]
Get:27 http://ams2.mirrors.digitalocean.com/ubuntu artful-updates/universe Translation-en [1,916 B]
Fetched 33.6 MB in 6s (0 B/s)
Hit http://security.ubuntu.com/ubuntu artful-security InRelease
Hit http://ams2.mirrors.digitalocean.com/ubuntu artful InRelease
Hit http://ams2.mirrors.digitalocean.com/ubuntu artful-updates InRelease
Hit https://apt.dockerproject.org/repo ubuntu-xenial InRelease
Hit https://repos.sonar.digitalocean.com/apt main InRelease
Ign https://download.docker.com/linux/ubuntu artful InRelease
Err https://download.docker.com/linux/ubuntu artful Release
  404  Not Found
Fetched 0 B in 0s (0 B/s)
Hit http://security.ubuntu.com/ubuntu artful-security InRelease
Hit https://apt.dockerproject.org/repo ubuntu-xenial InRelease
Hit http://ams2.mirrors.digitalocean.com/ubuntu artful InRelease
Hit https://repos.sonar.digitalocean.com/apt main InRelease
Ign https://download.docker.com/linux/ubuntu artful InRelease
Hit http://ams2.mirrors.digitalocean.com/ubuntu artful-updates InRelease
Err https://download.docker.com/linux/ubuntu artful Release
  404  Not Found
Fetched 0 B in 0s (0 B/s)

Error during update

A problem occurred during the update. This is usually some sort of
network problem, please check your network connection and retry.

E:The repository 'https://download.docker.com/linux/ubuntu artful
Release' does not have a Release file.


Restoring original system state

Aborting
```

**Comment by BigNerd95** [comment]
@seemethere 
```
NAME="Ubuntu"
VERSION="17.10 (Artful Aardvark)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 17.10"
VERSION_ID="17.10"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=artful
UBUNTU_CODENAME=artful

```

**Comment by seemethere** [comment]
@darwin there are no `artful` repositories yet which is why this PR just substitutes the `artful` for `zesty` when it designates the repository.

`artful` repositories will not be coming until the release of `17.11.0-ce`

**Comment by BigNerd95** [comment]
I solved with
```
sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu zesty stable"
```

**Comment by BigNerd95** [comment]
Oks :+1:

**Comment by darwin** [comment]
@seemethere ok, thanks for clarification. Will wait. I'm a linux noob.

**Comment by adililhan** [comment]
Well, actually, according the instruction, Docker repository can be added with the output of `lsb_release -cs`. However, if you are using `artful` then it won't be working. I think, there should be a "friendly reminder" on there.

Just sayin'

The instruction: https://docs.docker.com/engine/installation/linux/docker-ce/ubuntu/#install-using-the-repository

**Comment by FrenchBen** [comment]
@adililhan it's a valid point; but this was a patch on the `get.docker.com` install script to allow it to install on Artful.

**Pull request merged**
