### PR TITLE
add Ubuntu Cosmic (18.10)

### PR DESCRIPTION
**Pull request by twhitbeck**

### CODE REVIEW

**Comment by twhitbeck** [comment]
18.10 is officially out. I realize new builds won't be produced until the next stable, but I thought we ought to be ready for it. This is always a pain point for me, as I tend to upgrade asap and then I can't install Docker. Is there a good reason not to get ahead of the curve here?

**Comment by jose-bigio** [comment]
Related Issue: https://github.com/docker/docker-ce-packaging/pull/121

**Comment by thaJeztah** [comment]
@svendowideit I think packages for cosmic will go out with the 18.09.1 patch release; see the discussion on https://github.com/docker/docker-ce-packaging/pull/255

The nightly channel should have packages though

**Comment by seemethere** [comment]
Closing in favor of #86

**Pull request closed without merging**
