### PR TITLE
Add docker-compose-plugin package

### PR DESCRIPTION
**Pull request by debdutdeb**
Signed-off-by: Debdut Chakraborty <debdut.chakraborty@rocket.chat>

### CODE REVIEW

**Comment by debdutdeb** [comment]
@thaJeztah hey - this would be awesome to have :D

**Comment by geekgonecrazy** [comment]
Would make a huge difference in getting someone up and going with a docker-compose if they can install docker via this script and already have compose at their disposal.


Especially given how complicated installing compose on its own is if you look at the documentation.  It looks pretty intimidating

**Comment by thaJeztah** [comment]
Thanks for working on this, @debdutdeb - I had to make some other changes/preparations in https://github.com/docker/docker-install/pull/287, which conflicted with this PR, and am carrying your changes in https://github.com/docker/docker-install/pull/288 (kept your commit, but amended it with the version checks)

**Comment by debdutdeb** [comment]
Thanks Sebastian!

**Pull request closed without merging**
