### PR TITLE
rootless: update to 26.1.2

### PR DESCRIPTION
**Pull request by vvoland**
rootless: update to 26.1.2

### CODE REVIEW

**Comment by thaJeztah** [comment]
LOL, looks like shellcheck may have been updated?

```
In build/install.sh line 197:
version_compare() (
^-- SC2329 (info): This function is never invoked. Check usage (or ignored if invoked indirectly).

For more information:
  https://www.shellcheck.net/wiki/SC2329 -- This function is never invoked. C...
make: *** [Makefile:20: shellcheck] Error 1
Error: Process completed with exit code 2.
```

**Comment by vvoland** [comment]
Yeah, and it looks like a false positive, because it's used in `version_gte` which is used all around the script? 🤔

**Comment by thaJeztah** [comment]
Looks like a false positive though; `version_gte` calls `version_compare`; https://github.com/docker/docker-install/blob/6e61729e66af62fd54c0b659751a431be8f90f68/install.sh#L178-L183

**Comment by thaJeztah** [comment]
Oh! Race condition; yup; found the same indeed.

Maybe it doesn't like the `eval` (can we do it without? not sure)

**Comment by vvoland** [comment]
Getting rid of the `eval` doesn't help:
```
$ git diff --cached                                                                                                                                                                                                
diff --git a/install.sh b/install.sh
index 0734c02..dc7540c 100755
--- a/install.sh
+++ b/install.sh
@@ -179,7 +179,7 @@ version_gte() {
        if [ -z "$VERSION" ]; then
                        return 0
        fi
-       eval version_compare "$VERSION" "$1"
+       version_compare "$VERSION" "$1"
 }

 # version_compare compares two version strings (either SemVer (Major.Minor.Path),

$ make shellcheck                                                                                                                                                                                              
docker run --rm -v "/Users/pawel/c/docker-install":/v -w /v koalaman/shellcheck -eSC1091 -eSC1117 -eSC2317 build/install.sh

In build/install.sh line 197:
version_compare() (
^-- SC2329 (info): This function is never invoked. Check usage (or ignored if invoked indirectly).

For more information:
  https://www.shellcheck.net/wiki/SC2329 -- This function is never invoked. C...
make: *** [shellcheck] Error 1
```

**Comment by thaJeztah** [comment]
bummer! we should probably check if there's a ticket for this, or report it as bug (with a minimal reproducer).

Also wondering if it perhaps doesn't like that `version_gte` is defined _before_ `version_compare` (ISTR I ran into something like that somewhere)

**Comment by thaJeztah** [comment]
nope; no dice with that either. yup, sounds like just a plain'ol bug then

**Review by thaJeztah — APPROVED** [review]
LGTM

**Comment by vvoland** [comment]
Looks like it's a related to the fix for: https://github.com/koalaman/shellcheck/issues/2966

In previous versions we also had this issue, but it emitted a SC2317 for every line of this function:
<details>

```
In build/install.sh line 198:
        set +x
        ^----^ SC2317 (info): Command appears to be unreachable. Check usage (or ignore if invoked indirectly).


In build/install.sh line 200:
        yy_a="$(echo "$1" | cut -d'.' -f1)"
        ^-- SC2317 (info): Command appears to be unreachable. Check usage (or ignore if invoked indirectly).
                ^-----------------------^ SC2317 (info): Command appears to be unreachable. Check usage (or ignore if invoked indirectly).


In build/install.sh line 201:
        yy_b="$(echo "$2" | cut -d'.' -f1)"
        ^-- SC2317 (info): Command appears to be unreachable. Check usage (or ignore if invoked indirectly).
                ^-----------------------^ SC2317 (info): Command appears to be unreachable. Check usage (or ignore if invoked indirectly).


In build/install.sh line 202:
        if [ "$yy_a" -lt "$yy_b" ]; then
        ^-- SC2317 (info): Command appears to be unreachable. Check usage (or ignore if invoked indirectly).
           ^---------------------^ SC2317 (info): Command appears to be unreachable. Check usage (or ignore if invoked indirectly).


In build/install.sh line 203:
                return 1
                ^------^ SC2317 (info): Command appears to be unreachable. Check usage (or ignore if invoked indirectly).


In build/install.sh line 205:
        if [ "$yy_a" -gt "$yy_b" ]; then
        ^-- SC2317 (info): Command appears to be unreachable. Check usage (or ignore if invoked indirectly).
           ^---------------------^ SC2317 (info): Command appears to be unreachable. Check usage (or ignore if invoked indirectly).


In build/install.sh line 206:
                return 0
                ^------^ SC2317 (info): Command appears to be unreachable. Check usage (or ignore if invoked indirectly).


In build/install.sh line 208:
        mm_a="$(echo "$1" | cut -d'.' -f2)"
        ^-- SC2317 (info): Command appears to be unreachable. Check usage (or ignore if invoked indirectly).
                ^-----------------------^ SC2317 (info): Command appears to be unreachable. Check usage (or ignore if invoked indirectly).


In build/install.sh line 209:
        mm_b="$(echo "$2" | cut -d'.' -f2)"
        ^-- SC2317 (info): Command appears to be unreachable. Check usage (or ignore if invoked indirectly).
                ^-----------------------^ SC2317 (info): Command appears to be unreachable. Check usage (or ignore if invoked indirectly).


In build/install.sh line 212:
        mm_a="${mm_a#0}"
        ^--------------^ SC2317 (info): Command appears to be unreachable. Check usage (or ignore if invoked indirectly).


In build/install.sh line 213:
        mm_b="${mm_b#0}"
        ^--------------^ SC2317 (info): Command appears to be unreachable. Check usage (or ignore if invoked indirectly).


In build/install.sh line 215:
        if [ "${mm_a:-0}" -lt "${mm_b:-0}" ]; then
        ^-- SC2317 (info): Command appears to be unreachable. Check usage (or ignore if invoked indirectly).
           ^-- SC2317 (info): Command appears to be unreachable. Check usage (or ignore if invoked indirectly).


In build/install.sh line 216:
                return 1
                ^------^ SC2317 (info): Command appears to be unreachable. Check usage (or ignore if invoked indirectly).


In build/install.sh line 219:
        return 0
        ^------^ SC2317 (info): Command appears to be unreachable. Check usage (or ignore if invoked indirectly).


In build/install.sh line 736:
        exit 1
        ^----^ SC2317 (info): Command appears to be unreachable. Check usage (or ignore if invoked indirectly).
```

</details>


and we're ignoring the SC2317 completely:
https://github.com/docker/docker-install/blob/6e61729e66af62fd54c0b659751a431be8f90f68/Makefile#L6



After https://github.com/koalaman/shellcheck/commit/4f81dbe839091a06a5cfaea695cf1c451ff07565 this was fixed and now it produces one `SC2329` for the whole function.

So there's still a false positive I think, but we already were ignoring that one, so just ignoring the `SC2329` should give us the same behavior as before.

**Pull request merged**
