### PR TITLE
rootless-install.sh: bump up to 19.03.7

### PR DESCRIPTION
**Pull request by AkihiroSuda**

### CODE REVIEW

**Comment by AkihiroSuda** [comment]
Can we somehow automate this?

I suggest adding the latest version string ("19.03.7") to  a text file like https://download.docker.com/linux/static/stable/x86_64/LATEST

**Comment by AkihiroSuda** [comment]
@StefanScherer @thaJeztah @tonistiigi @tiborvass

**Comment by thaJeztah** [comment]
> I suggest adding the latest version string ("19.03.7") to a text file like
> https://download.docker.com/linux/static/stable/x86_64/LATEST

Could be good to have; we may have to consider what works best (also if we decide to move containerd and possible the cli to a separate tar)

**Comment by thaJeztah** [comment]
@tiborvass @silvin-lubecki ^^

**Comment by silvin-lubecki** [comment]
The checks are still on `Waiting for status` 🤔cc @thaJeztah @StefanScherer

**Comment by thaJeztah** [comment]
@silvin-lubecki yes, I think there's a bug on GitHub where, after you mark a check as "required", it will be _added_ to existing  PR's, but never actually run (or complete) 😞 

@AkihiroSuda could you do a force push to see if that helps?

**Comment by StefanScherer** [comment]
I've kicked off https://ci-next.docker.com/teams-core/job/get.docker.com/job/upload-rootless-install/5/ 
Something we want to convert into a GH action soon :-)

**Comment by thaJeztah** [comment]
Was thinking about that (didn't know how it got deployed). Would we need an option to make changes without them being deployed directly? (In case there's large changes for an upcoming release) guess we could use a feature branch for that or something 🤔

**Pull request merged**
