### PR TITLE
rootless-install.sh: bump up to 19.03.12

### PR DESCRIPTION
**Pull request by AkihiroSuda**

### CODE REVIEW

**Comment by StefanScherer** [comment]
Oh yes, it's about time. 

In the meantime I've created PR #182 to retrieve the latest release from GitHub.

**Comment by AkihiroSuda** [comment]
http://get.docker.com/rootless seems out of sync?

**Comment by StefanScherer** [comment]
Fixed. Thanks @AkihiroSuda 😅

**Comment by AkihiroSuda** [comment]
thanks

**Pull request merged**
